config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectTracking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
  <nav class="navbar bg-body-tertiary ">
    <div class="container-fluid">
      
      <img src="https://www.graphicsprings.com/filestorage/stencils/1d3c1e1d87e6021fe5e5ffb325fc53d3.svg" class="img-thumbnail" alt="Funny looking lobster on an tropic island with palm trees, AI generated i think">
      <div class="navbar-brand border border-dark rounded " > <%= link_to "Project Tracking", pages_home_path, {:style=>'color:#000000; text-decoration:none; margin-left: 5px; margin-right: 5px;', :class => "css_class"} %> </div>
      <div class="border border-dark rounded"> <a class="navbar-brand ms-2">Activity</a> </div>
      <div class="border border-dark rounded"> <a class="navbar-brand ms-2">Groups</a> </div>
      <div class="border border-dark rounded"> <a class="navbar-brand ms-2">To Do List</a> </div>
      <div class="border border-dark rounded"> <a class="navbar-brand ms-2">Calender</a> </div>
      <div class="border border-dark rounded"> <a class="navbar-brand ms-2">Meetings</a> </div>
      <div class="border border-dark rounded"> <a class="navbar-brand ms-2">Messages</a> </div>
      <div class="navbar-brand border border-dark rounded"> <%= link_to "Contact", pages_contact_path, {:style=>'color:#000000; text-decoration:none; margin-left: 5px; margin-right: 5px;', :class => "css_class"} %> </div>
      <form class="d-flex" role="search">
        <button class="btn btn-outline-dark" type="submit">Sign In</button>
        <button class="btn btn-outline-dark ms-2" type="submit">Sign Up</button>
      </form>
    </div>
  </nav>
  
    <!-- Inspiration: https://olympics.com/es/ (I thought we were remaking the website, some text is copied over) -->
    <div><hr>
      <%= yield %>
    </div><hr>
    
    <div class="bg-dark text-light">
      <div class="container"><hr> <!-- footer -->
        <div class="row">
          <div class="col"> <img src="https://dummyimage.com/200x200/000/fff" class="img-thumbnail" alt="example"> </div>
          
          <div class="col">
            <h3>Email Application</h3>
              <p>Send Emails</p>
              <p>Create Email Address</p>
              <p>Change Email</p>
              <p>Email Recovery</p>
          </div>
          <div class="col">
            <h3>Groups</h3>
              <p>Join New Group</p>
              <p>Edit/Leave Group</p>
              <p>Create New Group</p>
          </div>
          <div class="col">
            <h3>Calender</h3>
              <p>Add Calender Entires</p>
              <p>View Calender Entires</p>
          </div>
          <div class="col">
            <h3> Meetings</h3>
              <p>Join Meeting </p>
          </div>
          
        </div><hr>
        <div class="row mt-4">
          <div class="col"> <p> Activities </p> </div>
          <div class="col"> <p> Groups </p> </div>
          <div class="col"> <p> To Do List </p> </div>
          <div class="col"> <p> Calender </p> </div>
          <div class="col"> <p> Meetings </p> </div>
          <div class="col"> <p> Messages </p> </div>
        </div>
      <div>
      <div class="row">
        <div class="col text-center"> <h5>TM © 2O28 – Sean Derenas and BayPath Programming and Web Development – All Rights Reserved.</h5> </div>
      </div>
    </div>

  </body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="container bg-dark mb-5 pt-4">
  <div class="bg-body-secondary">
    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="https://dummyimage.com/1000x350/000/fff" class="d-block w-100" alt="example">
        </div>
        <div class="carousel-item">
          <img src="https://dummyimage.com/1000x350/000/fff" class="d-block w-100" alt="example">
        </div>
        <div class="carousel-item">
          <img src="https://dummyimage.com/1000x350/000/fff" class="d-block w-100" alt="example">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <div class="row mt-5">
      <div class="col mb-5">
        <img src="https://dummyimage.com/700x500/000/fff" class="img-thumbnail" alt="example">
      </div>
      <div class="col m-2 bg-light">
        <h1>Placeholder Esports Week Singapore Buy Your Tickets</h2>
        <div class="row m-4">
          <div class="col-12 m-3"> <button type="button" class="btn btn-dark" style="width: 100%;">Get your Tickets now!</button> </div>
          <div class="col-12 m-3"> <button type="button" class="btn btn-dark" style="width: 100%;">Placeholder Esports week</button> </div>
        </div>

      </div>
    </div>
  </div>








</div>